name: build-and-push
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@workflow-integration-tests
